blog/urls.py
from django.urls import path, include
from django.conf import settings
from .import views

urlpatterns = [
    path('',views.post_list, name='post_list'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<slug:slug>/', views.post_detail, name='post_detail'),
    path('post/<slug:slug>/edit/', views.post_edit, name='post_edit'),
    path('categories/', views.category_list, name='category_list'),
    path('categories/<int:pk>/post_by_categories/', views.category_wise_post, name='category_wise_post'),
    path('tags', views.tags, name='tags'),
    path('tags/<int:pk>/tag_wise_post/', views.tag_wise_post, name='tag_wise_post'),
    path("register", views.register, name="register"),
    path("login", views.user_login, name="user_login"),
    path("logout", views.user_logout, name="user_logout"),
    path("user_profile", views.user_profile, name="user_profile"),
    path('update_profile/<int:pk>/edit', views.update_profile, name='update_profile'),
    path('export/', views.export, name='export_user'),
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<slug:slug>/", views.DetailView.as_view(), name="detail"),
    path("<slug:slug>/results/", views.ResultsView.as_view(), name="results"),
    path("<slug:slug>/vote/", views.vote, name="vote"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('',include('blog.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'BLOG ADMIN'
admin.site.index_title = "Welcome to Blog Portal"

blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from autoslug import AutoSlugField
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator

SEX_CHOICES = (
    ('F', 'Female',),
    ('M', 'Male',),
    ('U', 'Unsure',),
)
RULE_CHOICES = (
    ('A', 'Author',),
    ('R', 'Reader',),
)
# Create your models here.

class User(AbstractUser):
    phone_no = models.PositiveIntegerField(validators=[MaxValueValidator(9999999999)], null=True,blank=True)
    gender = models.CharField(max_length=1,choices=SEX_CHOICES,)
    date_of_birth = models.DateField(null=True)
    company = models.CharField(max_length=100,null=True,blank=True)
    city = models.CharField(max_length=30)
    state = models.CharField(max_length=30)
    country = models.CharField(max_length=30)
    user_img = models.ImageField(upload_to='UserImg', blank=True, null=True)
    user_web =  models.URLField(max_length=250,null=True,blank=True)
    user_address = models.CharField(max_length=300) 
    rule = models.CharField(max_length=1,choices=RULE_CHOICES, null=True,blank=True)

    def __str__(self):
        return self.username

class Category(models.Model):
    name = models.CharField(max_length=60)
    desc = models.TextField()
    image = models.ImageField(upload_to='cat')
    slug = AutoSlugField(populate_from='name', unique=True, default=None, null=True)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=60)
    desc = models.TextField()
    image = models.ImageField(upload_to='cat')
        
    def __str__(self):
        return self.name

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)
    title = models.CharField(max_length=200)
    text = models.TextField()
    feature_img = models.ImageField(upload_to='post/feture',blank=True, null=True)
    thumbnail_img = models.ImageField(upload_to='post/thumbnail',blank=True, null=True)
    slug = AutoSlugField(populate_from='title', unique=True, default=None, null=True)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()
    
    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_date',]
    
    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'slug':self.slug})

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments',null=True)
    name = models.CharField(max_length=80)
    commenter_email = models.EmailField(max_length=200, blank=True)
    comment_content = models.TextField()
    commented_date = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')

    class Meta:
        ordering = ('commented_date',)

    def __str__(self):
        return 'Comment by {}'.format(self.name)

blog/forms.py
from django import forms
from .models import Post, Category, User, Comment
from django.contrib.auth.forms import UserCreationForm
from django.db.models import fields

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = '__all__'
        exclude = ('author','created_date','published_date',)


class RegisterForm(UserCreationForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)  
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)
    date_of_birth = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    class Meta:
        model = User
        fields = ['user_img','username','first_name','last_name','password1','password2','email','phone_no','gender','date_of_birth','company','city','state','country','user_web','user_address','rule']        

class LoginForm(forms.Form):
    username = forms.CharField(label='Please Enter email or username')
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','comment_content')

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['user_img','first_name', 'email', 'gender', 'date_of_birth', 'phone_no', 'city', 'state', 'country']

blog/views.py
import csv, os
from django.conf import settings
from django.shortcuts import render,redirect
from django.utils import timezone
from datetime import datetime
from .models import Post, Category, Tag, Comment, User
from django.shortcuts import render, get_object_or_404
from .forms import PostForm, RegisterForm, LoginForm, CommentForm, UserForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.http import HttpResponse


# Create your views here.
def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-created_date')
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            form.save_m2m()
            messages.success(request, f'You are post created succesfully.')
            return redirect('post_detail', slug=post.slug)
        else:
            messages.error(request, f'There is something went wrong.')
            return render(request, 'blog/post_new.html', {'form': form})
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

def post_edit(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            form.save_m2m()
            messages.success(request, f'Your post updated succesfully.')
            return redirect('post_detail', slug=post.slug)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

def category_list(request):
    categories = Category.objects.all().order_by('name')
    return render(request, 'blog/category_list.html', {'categories': categories})

def category_wise_post(request, pk):
    category = Category.objects.get(pk=pk)
    post_list = Post.objects.filter(category=category)
    return render(request, 'blog/category_wise_post.html', {'post_list': post_list})

def tags(request):
    tags = Tag.objects.all().order_by('name')
    return render(request, 'blog/tags.html', {'tags':tags})

def tag_wise_post(request, pk):
    tags = Tag.objects.get(pk=pk)
    post_list = Post.objects.filter(tags=tags)
    return render(request, 'blog/tag_wise_post.html', {'post_list': post_list})

def register(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            user = authenticate(
                    username=form.cleaned_data['username'],
                    password=form.cleaned_data['password1'],
                )
            if user is not None:
                login(request, user)
                messages.success(request, f' Your Account created and Now you are logged in succesfully.')
                return redirect('post_list')
        return render(request, 'blog/register.html', {'form':form})
    else:
        return render(request, 'blog/register.html', {'form':form})

def user_login(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            name=form.cleaned_data['username']
            password=form.cleaned_data['password1']
            try:
                try:
                    user = authenticate(
                        username=User.objects.get(username=name),
                        password=password,
                    )
                except:
                    user = authenticate(
                        username=User.objects.get(email__exact=name),
                        password=password,
                    )
            except Exception as e:
                messages.error(request, f'{e}')
                return render(request, 'blog/login.html', {'form':form})
            if user is not None:
                login(request, user)
                messages.success(request, f' You are logged in succesfully.')
                return redirect('post_list')
            else:
                messages.error(request, f'There is something went wrong.')
                return render(request, 'blog/login.html', {'form':form})
        else:
            messages.error(request, f'There is something went wrong.')
            return render(request, 'blog/login.html', {'form':form})
    else:
        return render(request, 'blog/login.html', {'form':form})

def user_logout(request):
    logout(request)
    messages.success(request, f'You are logged out succesfully.')
    return redirect('post_list')

def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    comments = post.comments.filter(active=True, parent__isnull=True).order_by('-commented_date')
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            parent_obj = None
            try:
                parent_id = int(request.POST.get('parent_id'))
            except:
                parent_id = None
            if parent_id:
                parent_obj = Comment.objects.get(id=parent_id)
                if parent_obj:
                    replay_comment = comment_form.save(commit=False)
                    replay_comment.parent = parent_obj
            new_comment = comment_form.save(commit=False)
            
            new_comment.post = post
            new_comment.save()
            return redirect(f'/post/{post.slug}')
    else:
        comment_form = CommentForm()
    return render(request,
                  'blog/post_detail.html',
                  {'post': post,
                   'comments': comments,
                   'comment_form': comment_form})

def user_profile(request):
    user = request.user
    return render(request, 'blog/user_profile.html', {'user':user})

def update_profile(request, pk):
    user = get_object_or_404(User, pk=pk)
    if request.method == "POST":
        form = UserForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            user = form.save(commit=False)
            user.author = request.user
            user.save()
            messages.success(request, f'User Details updated succesfully.')
            return redirect('user_profile')
    else:
        form = UserForm(instance=request.user)
    return render(request, 'blog/update_profile.html', {'form':form})

def export(request):
    # Generate a unique filename (e.g., timestamp or random string)
    timestamp = datetime.now().strftime('%Y%m%d%H%M%S')
    unique_filename = f'user_{timestamp}.csv'

    # Define the file path where the CSV will be stored on the server
    file_path = os.path.join(settings.MEDIA_ROOT, unique_filename)

    # Create and write the CSV file
    with open(file_path, 'w', newline='') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(['first_name', 'last_name', 'email', 'gender', 'date_of_birth', 'phone_no', 'city', 'state', 'country'])
        for user in User.objects.all().values_list('first_name', 'last_name', 'email', 'gender', 'date_of_birth', 'phone_no', 'city', 'state', 'country'):
            writer.writerow(user)

    # Serve the file for download
    with open(file_path, 'rb') as file:
        response = HttpResponse(file.read(), content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="user.csv"'

    return response

blog/templates/blog/author_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
        <article class="post">
            <h2>Author Detail</h2>
            {% if post_author.user_img %}
                <img src="{{post_author.user_img.url}}" alt="pic">
            {% endif %}
            <p>Name : {{postauthor.first_name}}</p>
            <p>Email : {{postauthor.email}}</p>
            <p>Gender : {{postauthor.gender}}</p>
            <p>DOB : {{postauthor.dob}}</p>
            <p>Phone Number : {{postauthor.phone_no}}</p>
            <p>City : {{postauthor.city}}</p>
            <p>State : {{postauthor.state}}</p>
        </article>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Django Girls blog</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
        <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css1/blog.css' %}">
    </head>
    <body>
        <header class="page-header navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ft">
                        <li class="nav-item ">
                          <a class="nav-link active" aria-current="page" href="{% url 'post_list' %}">Django Girls Blog</a> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        </li>
                        <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="{% url 'category_list' %}">Category</a>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        </li>
                        <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="{% url 'tags' %}">Tags</a>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        </li>
                        <li class="nav-item">
                          <a class="nav-link active" href="{% url 'polls:index' %}">Make Polls</a>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        </li>
                      {% if user.is_authenticated %}
                        <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="{% url 'post_new' %}">
                              {% include './icons/file-earmark-plus.svg' %}
                          </a>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        </li>
                    </ul>
                    <ul class="navbar-nav mb-2 mb-lg-0 ft">
                        <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="{% url 'user_profile' %}">{{request.user.first_name}}</a>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        </li>
                        <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="{% url 'user_logout' %}">Logout</a>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        </li>
                      {% else %}
                        <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="{% url 'user_login' %}">LogIn</a>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        </li>
                      {% endif %}
                    </ul>
                </div>
            </div>
        </header>
       {% include 'blog/messages.html' %}
        <main class="content container">
            <div class="row">
                <div class="col">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </main> 
    </body>
</html>

blog/templates/blog/category_list.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2>All Categories</h2>
    {% for category in categories %}
        <article class="post">
            <h2><a href="{% url 'category_wise_post' category.id %}">{{ category.name }}</a></h2>
            <p><img src="{{category.image.url}}" width="120"/></p>
            <p>{{ category.desc|linebreaksbr }}</p>
        </article>
    {% endfor %}
{% endblock %}

blog/templates/blog/category_wise_post.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in post_list %}
        <article class="post">
            <div class="card mb-3">
                <div class="card-body">
                <h2  class="card-title"><a href="{% url 'post_detail' slug=post.slug %}">{{ post.title }}</a></h2>
                <p class="card-text">{{ post.text|linebreaksbr }}.</p>
                <p><strong>Category:</strong> {{ post.category.name }}</p>
                <p><strong>Tags:</strong> {{ post.tags.all|join:", " }}</p>
                <p class="card-text"><small class="text-body-secondary">{{ post.published_date }}</small></p>
            </div>
        </div>
        </article>
    {% endfor %}
{% endblock %}

blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %} 
<div class="content-section col-md-8 col-md-offset-2">
  <center>
    <form method="POST" style="border: 1px solid black; margin: 4%; padding:10%; border-radius:1%;">
      {% csrf_token %}
        <fieldset class="form-group">
          {{ form|crispy}}
        </fieldset>
        <center>
          <button style="background: yellow; font-size: 1rem; padding:2%; margin:2%;" class="btn btn-outline-info" type="submit"><span class="glyphicon glyphicon-log-in"></span> &nbsp; login</button>
        </center>
        <br/>
        <sub style="text-align: left;"><a href="{% url 'register' %}" style="text-decoration: none; color: blue; padding:2%; cursor:pointer; margin-right:2%;">don't have account,sign up</a></sub>
    </form>
  </center>
 </div>
{% endblock %}

blog/templates/blog/messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
<article class="post">
  <div class="card mb-3">
      <img src="{{post.thumbnail_img.url}}" width="450" height="300" class="card-img-top" alt="...">
        <div class="card-body">
        <h5 class="card-title">{{ post.title }}</h5>
        <aside class="actions">
          {% if post.author == request.user %}
            <a class="btn btn-secondary" href="{% url 'post_edit' slug=post.slug %}">
              {% include './icons/pencil-fill.svg' %}
            </a>
          {% endif %}
        </aside>
        <p class="card-text">{{ post.text|linebreaksbr }}.</p>
        <p class="card-text"><small class="text-body-secondary">{{ post.published_date }}</small></p>
        <p><strong>Category:</strong> {{ post.category.name }}</p>
        <p><strong>Tags:</strong> {{ post.tags.all|join:", " }}</p>
        <p class="in">
          {% if post.author.user_img %}
              <img src="{{post.author.user_img.url}}" class="rounded_img" width="50" height="50"/>
          {% endif %}
          {% if post.author == request.user %}
          <span><a href="{% url 'user_profile' %}">{{ post.author.first_name }}</a></span>
          {% else %}
              <span>{{ post.author.first_name }}</span>
          {% endif %}
      </p>
      </div>
  </div>
</article>
<!-- comment section -->

<!-- Comments Form -->
<h2>Add a new comment</h2>
<form action="." method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <button type="submit">Add comment</button>
</form>

<!-- Comment with nested comments -->
{% for comment in comments %}
<div class="comment" >
    <p class="info" style="margin: 0px;">{{ comment.name }} | {{ comment.commented_date }}</p>
    {{ comment.comment_content|linebreaks }}

    {% for replay in comment.replies.all %}
    <p class="info" style="margin: 0px 26px;">{{ replay.name }} | {{ replay.commented_date }}</p>
    <li style="list-style-type: none; margin-left: 30px;">{{ replay.comment_content }}</li>
    {% endfor %}

    <button type="button" class="collapsible" style="margin-left: 0px;">Reply</button>

    <div class="content" style="display: none;">
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <!-- Hidden input for parent comment.id -->
            <input type="hidden" name="parent_id" value="{{ comment.id }}">
            <input class="btn btn-primary" type="submit" value="Reply">

        </form>
    </div>
</div>
{% empty %}
<h4>There are no comments yet.</h4>
{% endfor %}

<script>
var coll = document.getElementsByClassName("collapsible");
var i;

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.display === "block") {
      content.style.display = "none";
    } else {
      content.style.display = "block";
    }
  });
}
</script>

<!-- end comment section -->
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2>New post</h2>
    <form method="POST" enctype="multipart/form-data" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-secondary">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class='row card-group'>
        {% for post in posts %}
          <div class="col-4 mb-3">
            <div class="card h-100">
              <embed
                src="{{post.thumbnail_img.url}}" width="450" height="300"
                class="card-img-top"
                alt="..."
              />
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'post_detail' slug=post.slug %}">{{ post.title }}</a></h5>
                    <p class="card-text">{{ post.text|slice:250 }}...</p>
                    <p><strong>Category:</strong> {{ post.category.name }}</p>
                    <p><strong>Tags:</strong> {{ post.tags.all|join:", " }}</p>
                    <p class="in">
                    {% if post.author.user_img %}
                        <img src="{{post.author.user_img.url}}" class="rounded_img" width="50" height="50"/>
                    {% endif %}
                    {% if post.author == request.user %}
                    <span><a href="{% url 'user_profile' %}">{{ post.author.first_name }}</a></span>
                    {% else %}
                        <span>{{ post.author.first_name }}</span>
                    {% endif %}
                </p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">{{ post.published_date }}</small>
                </div>
            </div>
          </div>
        {% endfor %}
    </div>
{% endblock %}

blog/templates/blog/register.html
{% extends 'blog/base.html' %}
{% block content %}
<h2>Register</h2>
<form method="post" class="post-form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-secondary">Register</button>
</form>
{% endblock %}

blog/templates/blog/tag_wise_post.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in post_list %}
        <article class="post">
            <div class="card mb-3">
                <div class="card-body">
                <h2  class="card-title"><a href="{% url 'post_detail' slug=post.slug %}">{{ post.title }}</a></h2>
                <p class="card-text">{{ post.text|linebreaksbr }}.</p>
                <p><strong>Category:</strong> {{ post.category.name }}</p>
                <p><strong>Tags:</strong> {{ post.tags.all|join:", " }}</p>
                <p class="card-text"><small class="text-body-secondary">{{ post.published_date }}</small></p>
              </div>
          </div>
        </article>
    {% endfor %}
{% endblock %}

blog/templates/blog/tags.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2>All Tags</h2>
    {% for tag in tags %}
        <article class="post">
            <h2><p><a href="{% url 'tag_wise_post' tag.id %}">{{ tag.name }}</a></p></h2>
            <p><img src="{{tag.image.url}}" width="120"/></p>
            <p>{{ tag.desc }}</p>
        </article>
    {% endfor %}
{% endblock %}

blog/templates/blog/update_profile.html
{% extends 'blog/base.html' %}
{% block content %}
<h2>Update Profile</h2>
<form method="POST" class="post-form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-secondary">Update</button>
</form>

{% endblock %}

blog/templates/blog/user_profile.html
{% extends 'blog/base.html' %}
{% load static %}   
{% block content %}
        <article class="post">
            {% if user.user_img %}
                <img src="{{user.user_img.url}}" width="200" alt="">
            {% endif %}
            <a href="{% url 'update_profile' pk=user.pk %}"><i class="bi bi-pencil-square"></i></a>
            <p>Name : {{user.first_name}}</p>
            <p>Email            : {{user.email}}</p>
            <p>Gender           : {{user.gender}}</p>
            <p>DOB              : {{user.date_of_birth}}</p>
            <p>Phone number     : {{user.phone_no}}</p>
            <p>City             : {{user.city}}</p>
            <p>State            : {{user.state}}</p>
            <p>Country          : {{user.country}}</p>
        </article>
{% endblock %}